import Head from 'next/head'
import {ThemeProvider} from 'styled-components'
import {Navbar} from '../components/Navbar'

interface Itheme {
    colors: {
        primary: string
        secondary: string
    }
    media: {
        phone: string
        tablet: string
    }
}

const theme: Itheme = {
    colors: {
        primary: '#999999',
        secondary: 'blue',
    },
    media: {
        phone: '(max-width: 425px)',
        tablet: '(max-width: 768px) and (min-width: 425px)',
    }
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <ThemeProvider theme={theme}>
                <Navbar/>
            </ThemeProvider>
        </>
    )
}
